
create table MARKETS (
      SYMBOL  VARCHAR(25) PRIMARY KEY
    , NANE    VARCHAR(256) NOT NULL
    , ZONE_ID VARCHAR(256) NOT NULL
    , DESCR   VARCHAR(1024) NOT NULL
    , DEF_OPEN_TIME  TIME
    , DEF_CLOSE_TIME TIME
);
