
create table FX_RATES (
      CUR1  VARCHAR(3) NOT NULL
    , CUR2  VARCHAR(3) NOT NULL
    , MARKET_SYMBOL VARCHAR(25) NOT NULL
    , MARKET_DATE   DATE NOT NULL
    , MARKET_DATE_TIME DATETIME NOT NULL
    , DATE_TIME TIMESTAMP WITH TIME ZONE NOT NULL

    , BID NUMERIC NOT NULL
    , ASK NUMERIC NOT NULL

    --, HIGH NUMERIC
    --, LOW NUMERIC
    --, HIGH_52_WEEK NUMERIC
    --, LOW_52_WEEK NUMERIC
    --, PREV_CLOSE NUMERIC
    --, OPEN NUMERIC
    --, CLOSE NUMERIC
    --, CHANGE NUMERIC
    --, CHANGE_PRC NUMERIC -- change percent
    --, VOLUME NUMERIC
    --, VOLUME_3M NUMERIC

    , PRIMARY KEY (CUR1, CUR2)
);
